# Installing new packages

In [1]:
# Everything you'll need is probably pre-installed
# Use !pip install pacakge_name

!pip install numpy

# Imports



In [2]:
import torch
import torchvision
import numpy as np

# Connecting Google Drive to **Collab**

In [3]:
from google.colab import drive
drive.mount("/content/gdrive/")

Mounted at /content/gdrive/


# CUDA Basics

In [4]:
# Checking if we have a GPU available

print(f"Cuda is available: {torch.cuda.is_available()}")
print(f"Number of GPUs: {torch.cuda.device_count()}")

Cuda is available: True
Number of GPUs: 1


In [5]:
# Simple Tensors

tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [6]:
# Moving the tensor to GPU

tensor = tensor.to('cuda')
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [7]:
# Tensors must be on the same device

tensor_a = torch.rand(3,4)
tensor_b = torch.rand(3,4).to('cuda')
out = tensor_a + tensor_b

RuntimeError: ignored

# Tensor Operations

In [8]:
# Concatination
tensor = torch.rand(size=(1,3,224,224))
t0 = torch.cat([tensor, tensor, tensor], dim=0)
print(tensor.shape)
print(t0.shape)

torch.Size([1, 3, 224, 224])
torch.Size([3, 3, 224, 224])


In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(tensor.shape)
print(t1.shape)

torch.Size([1, 3, 224, 224])
torch.Size([1, 9, 224, 224])


In [ ]:
t2 = torch.cat([tensor, tensor, tensor], dim=2)
print(tensor.shape)
print(t2.shape)

torch.Size([1, 3, 224, 224])
torch.Size([1, 3, 672, 224])


In [9]:
# Slicing

tensor = torch.ones(4, 4) * 2
print(tensor)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])


In [10]:
tensor[:,1] = 0
print(tensor)

tensor([[2., 0., 2., 2.],
        [2., 0., 2., 2.],
        [2., 0., 2., 2.],
        [2., 0., 2., 2.]])


In [11]:
# Multipication

# This computes the element-wise product

print(f"tensor.mul(tensor): \n{tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor: \n{tensor * tensor}")

tensor.mul(tensor): 
tensor([[4., 0., 4., 4.],
        [4., 0., 4., 4.],
        [4., 0., 4., 4.],
        [4., 0., 4., 4.]]) 

tensor * tensor: 
tensor([[4., 0., 4., 4.],
        [4., 0., 4., 4.],
        [4., 0., 4., 4.],
        [4., 0., 4., 4.]])


In [12]:
# This computes the matrix multipication:

print(f"tensor.matmul(tensor.T) \n{tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n{tensor @ tensor.T}")

tensor.matmul(tensor.T) 
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.]]) 

tensor @ tensor.T 
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.]])


In [ ]:
# In-place operations
# adding a "_" after the operator name changes the tensor in-place
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[2., 0., 2., 2.],
        [2., 0., 2., 2.],
        [2., 0., 2., 2.],
        [2., 0., 2., 2.]]) 

tensor([[7., 5., 7., 7.],
        [7., 5., 7., 7.],
        [7., 5., 7., 7.],
        [7., 5., 7., 7.]])


In [ ]:
# View

a = torch.arange(1, 17)
print(a)
print()

a = a.view(4, 4)
print(a)
print()

a = a.view(16,-1)
print(a)
print()

a = a.view(2,2,4)
print(a)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16]])

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]]])


# Comparison GPU vs CPU

In [13]:
import time
b = torch.ones(4000,4000).to('cpu')
tick = time.time()
for _ in range(2000):
    b += b
print(f'Runtime: {(time.time()-tick)} [s]')

Runtime: 16.593876600265503 [s]


In [14]:
tick = time.time()
b = torch.ones(4000,4000).to('cuda')
for _ in range(2000):
    b += b
print(f'Runtime: {(time.time()-tick)} [s]')

Runtime: 0.8716163635253906 [s]


# First Network

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class LeNet5(nn.Module):

    def __init__(self):
        super(LeNet5, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution kernel
        self.conv1 = nn.Conv2d(in_channels=1, 
                               out_channels=6, 
                               kernel_size=5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(in_features=16 * 5 * 5, 
                             out_features=120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square, you can specify with a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = torch.flatten(x, 1) # flatten all dimensions except the batch dimension
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def forward(self, x):
        print("Input shape:", x.shape)
        x = self.conv1(x)
        print("After conv1:", x.shape)
        x = F.relu(x)
        x = F.max_pool2d(x, (2, 2)) # Max pooling over a (2, 2) window (If the size is a square, you can specify with a single number)
        print("After maxpool1d_1:", x.shape)
        x = self.conv2(x)
        print("After conv2", x.shape)
        x = F.relu(x)
        x = F.max_pool2d(x, 2)
        print("After maxpool1d_2:", x.shape)
        x = torch.flatten(x, 1) # flatten all dimensions except the batch dimension
        print("After flatten:", x.shape)
        x = self.fc1(x)
        x = F.relu(x)
        print("After fc1:", x.shape)
        x = self.fc2(x)
        x = F.relu(x)
        print("After fc2:", x.shape)
        x = self.fc3(x)
        print("After fc3:", x.shape)
        return x




net = LeNet5()
print(net)

LeNet5(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [ ]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

Input shape: torch.Size([1, 1, 32, 32])
After conv1: torch.Size([1, 6, 28, 28])
After maxpool1d_1: torch.Size([1, 6, 14, 14])
After conv2 torch.Size([1, 16, 10, 10])
After maxpool1d_2: torch.Size([1, 16, 5, 5])
After flatten: torch.Size([1, 400])
After fc1: torch.Size([1, 120])
After fc2: torch.Size([1, 84])
After fc3: torch.Size([1, 10])
tensor([[ 0.0184,  0.0095, -0.1500, -0.0758,  0.0769,  0.1316,  0.0142, -0.0158,
         -0.0828,  0.0127]], grad_fn=<AddmmBackward>)
